version: '2'
services:
  runner94:
    build:
      context: .
      dockerfile: 9.4.Dockerfile
    image: pg_sample_94
    links:
      - pg94
  runner95:
    build:
      context: .
      dockerfile: 9.5.Dockerfile
    image: pg_sample_95
    links:
      - pg95
  runner954:
    build:
      context: .
      dockerfile: 9.5.4.Dockerfile
    image: pg_sample_954
    links:
      - pg954
  pg94:
    image: postgres:9.4
  pg95:
    image: postgres:9.5
  pg954:
    image: postgres:9.5.4
  pg96:
    image: postgres:9.6
  runner96:
    build:
      context: .
      dockerfile: 9.6.Dockerfile
    image: pg_sample_96
    links:
      - pg96
  runnerdev:
    build:
      context: .
      dockerfile: runner.dev.Dockerfile
    image: pg_sample_dev
    links:
      - pgdev
  pgdev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: postgresql:dev
